name: d1_toolbox
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - docopt=0.6.2
  - idna=3.11
  - iniconfig=2.3.0
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libmpdec=4.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - ncurses=6.5
  - openssl=3.0.18
  - packaging=25.0
  - pip=25.3
  - pluggy=1.5.0
  - pthread-stubs=0.3
  - pycparser=2.21
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.14.2
  - python-json-logger=4.0.0
  - python_abi=3.14
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025b
  - urllib3=2.6.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - attrs==25.4.0
      - cryptography==46.0.3
      - dataone-common==3.5.2
      - dataone-libclient==3.5.2
      - frozenlist==1.8.0
      - iso8601==2.1.0
      - multidict==6.7.0
      - propcache==0.4.1
      - pyasn1==0.6.1
      - pyjwt==2.10.1
      - pyparsing==3.3.1
      - pyxb-x==1.2.6.3
      - rdflib==7.5.0
      - requests-toolbelt==1.0.0
      - yarl==1.22.0
      - zipstream==1.1.4
prefix: /home/servilla/miniconda3/envs/d1_toolbox
